import { basePrisma } from "@/lib/prisma"
import { notFound } from "next/navigation"
import Link from "next/link"
import { formatDate, formatCurrency } from "@/utils/formatters"
import { StatusBadge } from "@/components/ui/status-badge"
import { TrackButton } from "@/components/dispatch/track-button"
import { FileText, Download, Eye, ArrowLeft, Calendar, MapPin, Building, FolderOpen } from "lucide-react"

interface SuperAdminProjectDetailPageProps {
  params: Promise<{ id: string }>
}

export default async function SuperAdminProjectDetailPage({ params }: SuperAdminProjectDetailPageProps) {
  const { id } = await params

  // Fetch the project and related data
  const project = await basePrisma.project.findUnique({
    where: { id },
    include: {
      poc: { select: { id: true, name: true, email: true, phone: true, role: true } },
      client: { select: { id: true, name: true, email: true, phone: true, role: true } },
      tenantClient: { select: { id: true, companyName: true, companyLogoUrl: true } },
      collaterals: true,
      statusHistory: { orderBy: { timestamp: "desc" } },
      files: true,
      dispatch: true,
      approval: true,
    },
  })

  if (!project) {
    notFound()
  }

  // Files categorized by type
  const poFiles = project.files.filter((f) => f.type === "PO")
  const challanFiles = project.files.filter((f) => f.type === "CHALLAN")
  const invoiceFiles = project.files.filter((f) => f.type === "INVOICE")

  // Timeline computation matching client-side flow
  const getStatusHistory = (status: string) =>
    project.statusHistory.find((h) => h.status === status)

  const timelineSteps = [
    {
      title: "Order Received",
      date: project.createdAt,
      note: `Project created by ${project.poc?.name || project.pocName || "Unknown"}${project.branch ? ` • ${project.branch}` : ""}`,
      done: true,
    },
    {
      title: "Project Approved",
      date: getStatusHistory("APPROVED")?.timestamp ?? project.approval?.approvedAt ?? null,
      note: (() => {
        if (project.approval?.status === "APPROVED") {
          return "Project approved by Admin"
        }
        if (project.approval?.status === "REJECTED") {
          return "Project rejected - needs revision"
        }
        return "Pending admin approval"
      })(),
      done: project.approval?.status === "APPROVED" || !!getStatusHistory("APPROVED"),
      active: project.status === "REQUESTED" || project.approval?.status === "PENDING",
    },
    {
      title: "PI Created",
      date: project.piGeneratedAt ?? null,
      note: project.piNumber && project.piPdfUrl
        ? `Proforma Invoice ${project.piNumber} generated by ${project.poc?.name || project.pocName || "Unknown"}`
        : "Waiting for PI generation",
      done: !!project.piNumber && !!project.piPdfUrl,
      active: project.approval?.status === "APPROVED" && (!project.piNumber || !project.piPdfUrl),
    },
    {
      title: "PI Verified",
      date: project.piVerifiedAt ?? null,
      note: (() => {
        if (project.piStatus === "VERIFIED") {
          return "PI verified by Admin - ready to proceed"
        }
        if (project.piStatus === "REJECTED") {
          return "PI rejected - needs regeneration"
        }
        if (project.piNumber) {
          return "PI pending admin verification"
        }
        return "Waiting for PI generation"
      })(),
      done: project.piStatus === "VERIFIED",
      active: project.piStatus === "PENDING",
    },
    {
      title: "PO Generated",
      date: poFiles[0]?.uploadedAt ?? null,
      note: poFiles.length > 0
        ? "Purchase Order received from client"
        : "Waiting for Purchase Order",
      done: poFiles.length > 0,
      active: project.piStatus === "VERIFIED" && poFiles.length === 0,
    },
    {
      title: "Material Under Production",
      date: getStatusHistory("PRINTING")?.timestamp ?? null,
      note: getStatusHistory("PRINTING")?.note || "Production in progress",
      done: !!getStatusHistory("PRINTING") || ["PRINTING", "DISPATCHED", "DELIVERED"].includes(project.status),
      active: project.status === "APPROVED" && poFiles.length > 0,
    },
    {
      title: "Material Dispatched",
      date: project.dispatch?.dispatchDate ?? null,
      note: (() => {
        if (!project.dispatch) return "Waiting for dispatch"
        const dispatchInfo = `Shipped via ${project.dispatch.courier}`
        const tracking = project.dispatch.trackingId ? ` • Tracking: ${project.dispatch.trackingId}` : ""
        return dispatchInfo + tracking
      })(),
      done: !!project.dispatch?.dispatchDate || ["DISPATCHED", "DELIVERED"].includes(project.status),
      active: project.status === "PRINTING" && challanFiles.length > 0,
    },
    {
      title: "Challan Uploaded",
      date: challanFiles[0]?.uploadedAt ?? null,
      note: challanFiles.length > 0 ? "Delivery challan uploaded" : "Pending challan",
      done: challanFiles.length > 0,
      active: project.status === "DISPATCHED",
    },
    {
      title: "Tax Invoice Generated",
      date: invoiceFiles[0]?.uploadedAt ?? null,
      note: invoiceFiles.length > 0 ? "Tax invoice generated" : "Pending invoice",
      done: invoiceFiles.length > 0,
      active: project.status === "DISPATCHED",
    },
  ]

  // Cost calculations
  const itemsBaseCost = project.collaterals.reduce((sum, c) => sum + c.totalPrice, 0)
  const itemsGst = project.collaterals.reduce((sum, c) => sum + c.gstAmount, 0)
  const packingBaseCost = project.packingCharges || 0
  const packingGst = packingBaseCost * ((project.packingChargesGstRate ?? 18) / 100)
  const totalBaseCost = itemsBaseCost + packingBaseCost
  const totalGst = itemsGst + packingGst
  const grandTotal = project.grandTotal || (totalBaseCost + totalGst)

  return (
    <div className="detail-container" style={{ padding: "24px" }}>
      {/* Breadcrumb Navigation */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '24px', fontSize: '14px', color: 'var(--gray-600)' }}>
        <Link href="/superadmin/projects" style={{ color: 'var(--axis-accent)', textDecoration: 'none', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px' }}>
          <ArrowLeft size={16} /> Back to All Projects
        </Link>
      </div>

      {/* Project Header */}
      <div className="detail-header">
        <div className="detail-header-top">
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '12px' }}>
              <h1 style={{ fontSize: '32px', fontWeight: 800, margin: 0, color: 'var(--gray-900)' }}>{project.name}</h1>
              <StatusBadge status={project.status} />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '24px', fontSize: '14px', color: 'var(--gray-600)' }}>
              <span><strong>Project ID:</strong> <span className="project-id">{project.projectId}</span></span>
              <span><strong>PI Number:</strong> <span className="font-mono">{project.piNumber || "—"}</span></span>
              <span><strong>Created:</strong> {formatDate(project.createdAt)}</span>
            </div>
          </div>
          <div className="detail-actions">
            <span style={{ fontSize: '12px', padding: '6px 12px', background: 'var(--gray-100)', borderRadius: '6px', fontWeight: 600, color: 'var(--gray-600)' }}>
              View-Only Mode
            </span>
          </div>
        </div>

        {/* Detail Grid */}
        <div className="detail-grid">
          <div className="detail-field">
            <span className="detail-label">Order Date</span>
            <span className="detail-value">{formatDate(project.createdAt)}</span>
          </div>
          <div className="detail-field">
            <span className="detail-label">Assigned To</span>
            <div className="detail-value" style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
              {/* POC */}
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', whiteSpace: 'nowrap' }}>
                {project.poc?.name || project.pocName || "—"}
                <span style={{
                  fontSize: '10px',
                  padding: '2px 8px',
                  borderRadius: '9999px',
                  backgroundColor: 'rgba(217, 119, 6, 0.1)',
                  color: '#d97706',
                  fontWeight: 500,
                  border: '1px solid rgba(217, 119, 6, 0.2)',
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '3px'
                }}>
                  <span style={{ width: '4px', height: '4px', borderRadius: '50%', backgroundColor: '#d97706' }}></span>
                  POC
                </span>
              </span>
              {/* on behalf of */}
              {(project.client || project.clientName) && (
                <span style={{ color: 'var(--gray-400)', fontSize: '12px', paddingLeft: '8px' }}>
                  on behalf of
                </span>
              )}
              {/* Client User */}
              {(project.client || project.clientName) && (
                <span style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', whiteSpace: 'nowrap' }}>
                  {project.client?.name || project.clientName}
                  <span style={{
                    fontSize: '10px',
                    padding: '2px 8px',
                    borderRadius: '9999px',
                    backgroundColor: 'rgba(2, 132, 199, 0.1)',
                    color: '#0284c7',
                    fontWeight: 500,
                    border: '1px solid rgba(2, 132, 199, 0.2)',
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '3px'
                  }}>
                    <span style={{ width: '4px', height: '4px', borderRadius: '50%', backgroundColor: '#0284c7' }}></span>
                    CLIENT
                  </span>
                </span>
              )}
            </div>
          </div>
          <div className="detail-field">
            <span className="detail-label">Client Organization</span>
            <span className="detail-value">
              {project.tenantClient ? (
                <Link
                  href={`/superadmin/admins/${project.tenantClient.id}`}
                  style={{ color: "#8b5cf6", textDecoration: "none", fontWeight: 700 }}
                  className="hover:underline"
                >
                  {project.tenantClient.companyName}
                </Link>
              ) : (
                "—"
              )}
            </span>
          </div>
          <div className="detail-field">
            <span className="detail-label">Location</span>
            <span className="detail-value">{project.location}{project.state ? `, ${project.state}` : ""}</span>
          </div>
          <div className="detail-field">
            <span className="detail-label">Branch</span>
            <span className="detail-value">{project.branch || "—"}</span>
          </div>
          <div className="detail-field" style={{ gridColumn: '1 / -1' }}>
            <span className="detail-label">Delivery Address</span>
            <span className="detail-value">
              {project.recipientName ? `${project.recipientName} | ` : ""}
              {project.recipientContact ? `${project.recipientContact} | ` : ""}
              {project.recipientBranch ? `${project.recipientBranch}, ` : ""}
              {project.location}{project.state ? `, ${project.state}` : ""}, India
            </span>
          </div>
          {project.description && (
            <div className="detail-field" style={{ gridColumn: '1 / -1' }}>
              <span className="detail-label">Description</span>
              <span className="detail-value">{project.description}</span>
            </div>
          )}
          {project.instructions && (
            <div className="detail-field" style={{ gridColumn: '1 / -1' }}>
              <span className="detail-label">Special Instructions</span>
              <span className="detail-value">{project.instructions}</span>
            </div>
          )}
        </div>
      </div>

      {/* Main Content Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 400px', gap: '24px' }}>
        {/* Left Column */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          {/* Items & Collaterals */}
          <div className="card">
            <div className="card-header">
              <h3 className="card-title">Items & Collaterals</h3>
            </div>
            <div className="card-body">
              <div className="items-list">
                {project.collaterals.map((c) => (
                  <div key={c.id} className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                      <strong>{c.itemName}</strong>
                      <div style={{ fontSize: '12px', color: 'var(--gray-600)', marginTop: '2px' }}>
                        Quantity: {c.quantity.toLocaleString("en-IN")} @ {formatCurrency(c.unitPrice)}
                        {c.specification ? ` • Spec: ${c.specification}` : ""}
                      </div>
                    </div>
                    <div style={{ fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
                      {formatCurrency(c.totalPrice)}
                    </div>
                  </div>
                ))}
                {project.packingCharges != null && project.packingCharges > 0 && (
                  <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'rgba(59, 130, 246, 0.05)', marginTop: '8px', padding: '12px', borderRadius: '6px', border: '1px dashed var(--gray-300)' }}>
                    <div>
                      <strong>Packaging Charges</strong>
                      <div style={{ fontSize: '12px', color: 'var(--gray-600)', marginTop: '2px' }}>GST @ {project.packingChargesGstRate ?? 18}%</div>
                    </div>
                    <div style={{ fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
                      {formatCurrency(project.packingCharges)}
                    </div>
                  </div>
                )}
                <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '12px', background: 'var(--gray-100)', marginTop: '12px', padding: '12px', borderRadius: '6px' }}>
                  <span style={{ fontWeight: 700, fontSize: '13px' }}>Total Project Cost (excl. GST)</span>
                  <span style={{ fontSize: '15px', color: 'var(--axis-primary)', fontFamily: 'var(--font-mono)', fontWeight: 700 }}>
                    {formatCurrency(itemsBaseCost + packingBaseCost)}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Cost Breakdown */}
          <div className="card">
            <div className="card-header">
              <h3 className="card-title">Cost Breakdown</h3>
            </div>
            <div className="card-body">
              <div className="items-list" style={{ background: 'var(--gray-0)', padding: '16px', borderRadius: 'var(--radius-md)' }}>
                {/* Items Base Cost */}
                <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--gray-200)' }}>
                  <span style={{ color: 'var(--gray-600)' }}>Items Cost (excl. GST):</span>
                  <span style={{ fontWeight: 600, fontFamily: 'var(--font-mono)' }}>
                    {formatCurrency(itemsBaseCost)}
                  </span>
                </div>
                {/* Packing Charges */}
                {packingBaseCost > 0 && (
                  <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--gray-200)' }}>
                    <span style={{ color: 'var(--gray-600)' }}>Packing Charges:</span>
                    <span style={{ fontWeight: 600, fontFamily: 'var(--font-mono)' }}>
                      {formatCurrency(packingBaseCost)}
                    </span>
                  </div>
                )}
                {/* Total Base Cost */}
                <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--gray-200)', background: 'rgba(0,0,0,0.02)' }}>
                  <span style={{ color: 'var(--gray-700)', fontWeight: 600 }}>Total Base Cost:</span>
                  <span style={{ fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
                    {formatCurrency(totalBaseCost)}
                  </span>
                </div>
                {/* GST on Items */}
                <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--gray-200)' }}>
                  <span style={{ color: 'var(--gray-600)' }}>GST on Items:</span>
                  <span style={{ fontWeight: 600, fontFamily: 'var(--font-mono)' }}>
                    {formatCurrency(itemsGst)}
                  </span>
                </div>
                {/* GST on Packing */}
                {packingBaseCost > 0 && (
                  <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--gray-200)' }}>
                    <span style={{ color: 'var(--gray-600)' }}>GST on Packing ({project.packingChargesGstRate ?? 18}%):</span>
                    <span style={{ fontWeight: 600, fontFamily: 'var(--font-mono)' }}>
                      {formatCurrency(packingGst)}
                    </span>
                  </div>
                )}
                {/* Total GST */}
                <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--gray-200)', background: 'rgba(0,0,0,0.02)' }}>
                  <span style={{ color: 'var(--gray-700)', fontWeight: 600 }}>Total GST:</span>
                  <span style={{ fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
                    {formatCurrency(totalGst)}
                  </span>
                </div>
                {/* Grand Total */}
                <div className="item-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '12px', padding: '12px 0', borderBottom: 'none', marginTop: '8px', borderTop: '2px solid var(--gray-300)' }}>
                  <span style={{ color: 'var(--gray-900)', fontSize: '14px', fontWeight: 700 }}>Total Amount (incl. GST)</span>
                  <span style={{ fontSize: '17px', color: 'var(--axis-primary)', fontFamily: 'var(--font-mono)', fontWeight: 700 }}>
                    {formatCurrency(grandTotal)}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Lead Tracking & ROI */}
          <div className="card">
            <div className="card-header">
              <div>
                <h3 className="card-title">Lead Tracking & ROI</h3>
                <p style={{ fontSize: '13px', color: 'var(--gray-500)', margin: '4px 0 0 0' }}>Campaign results entered by tenant</p>
              </div>
            </div>
            <div className="card-body">
              <div className="detail-grid">
                <div className="detail-field">
                  <span className="detail-label">Leads Generated</span>
                  <span className="detail-value" style={{ fontSize: '24px', fontWeight: 700, color: 'var(--axis-primary)' }}>
                    {project.leadsGenerated || 0}
                  </span>
                </div>
                <div className="detail-field">
                  <span className="detail-label">Leads Converted</span>
                  <span className="detail-value" style={{ fontSize: '24px', fontWeight: 700, color: 'var(--color-success)' }}>
                    {project.leadsConverted || 0}
                  </span>
                </div>
                <div className="detail-field">
                  <span className="detail-label">Cost Per Lead</span>
                  <span className="detail-value" style={{ fontFamily: 'var(--font-mono)', fontWeight: 600 }}>
                    {project.leadsGenerated ? formatCurrency(grandTotal / project.leadsGenerated) : '—'}
                  </span>
                </div>
                <div className="detail-field">
                  <span className="detail-label">Cost Per Acquisition</span>
                  <span className="detail-value" style={{ fontFamily: 'var(--font-mono)', fontWeight: 600 }}>
                    {project.leadsConverted ? formatCurrency(grandTotal / project.leadsConverted) : '—'}
                  </span>
                </div>
              </div>
              {(project.leadsGenerated ?? 0) > 0 && (
                <div style={{ marginTop: '16px', padding: '12px', background: 'rgba(16, 185, 129, 0.1)', borderRadius: 'var(--radius-md)', borderLeft: '3px solid var(--color-success)' }}>
                  <p style={{ fontSize: '13px', color: 'var(--gray-600)', margin: 0 }}>
                    <strong>Conversion Rate:</strong> {(((project.leadsConverted ?? 0) / (project.leadsGenerated ?? 1)) * 100).toFixed(1)}%
                  </p>
                </div>
              )}
            </div>
          </div>

          {/* Dispatch & Delivery Information */}
          <div className="card">
            <div className="card-header">
              <h3 className="card-title">Dispatch & Delivery Information</h3>
            </div>
            <div className="card-body">
              <div className="detail-grid">
                <div className="detail-field">
                  <span className="detail-label">Dispatch Date</span>
                  <span className="detail-value">{project.dispatch?.dispatchDate ? formatDate(project.dispatch.dispatchDate) : <span style={{ color: 'var(--gray-400)' }}>Not yet dispatched</span>}</span>
                </div>
                <div className="detail-field">
                  <span className="detail-label">Expected Delivery</span>
                  <span className="detail-value">{project.dispatch?.expectedDelivery ? formatDate(project.dispatch.expectedDelivery) : project.deliveryDate ? formatDate(project.deliveryDate) : <span style={{ color: 'var(--gray-400)' }}>Not set</span>}</span>
                </div>
                <div className="detail-field">
                  <span className="detail-label">Courier Partner</span>
                  <span className="detail-value">{project.dispatch?.courier || <span style={{ color: 'var(--gray-400)' }}>Not assigned</span>}</span>
                </div>
                <div className="detail-field">
                  <span className="detail-label">Tracking Number</span>
                  <span className="detail-value font-mono" style={{ color: 'var(--axis-accent)' }}>{project.dispatch?.trackingId || <span style={{ color: 'var(--gray-400)' }}>Not available</span>}</span>
                </div>
              </div>
              {project.dispatch?.trackingId && (
                <div style={{ marginTop: '16px' }}>
                  <TrackButton
                    courier={project.dispatch.courier}
                    trackingId={project.dispatch.trackingId}
                    dispatchDate={project.dispatch.dispatchDate}
                    expectedDelivery={project.dispatch.expectedDelivery}
                    actualDelivery={project.dispatch.actualDelivery}
                    variant="secondary"
                    fullWidth
                  />
                </div>
              )}
            </div>
          </div>

          {/* Proforma Invoice (PI) Section */}
          <div className="card">
            <div className="card-header">
              <h3 className="card-title">Proforma Invoice (PI)</h3>
            </div>
            <div className="card-body" style={{ padding: "0 24px 24px" }}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  padding: "16px 20px",
                  background: "var(--gray-50)",
                  borderRadius: "8px",
                  border: "1px solid var(--gray-200)",
                }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                  <FileText size={24} color="var(--axis-primary)" />
                  <div>
                    <h3 style={{ margin: 0, fontSize: "16px", fontWeight: 600, color: "var(--gray-900)" }}>
                      Proforma Invoice (PI)
                    </h3>
                    {project.piNumber ? (
                      <p style={{ margin: "4px 0 0 0", fontSize: "14px", color: "var(--gray-600)" }}>
                        {project.piNumber}
                        {project.piGeneratedAt && (
                          <span style={{ marginLeft: "8px" }}>
                            • Generated {formatDate(project.piGeneratedAt)}
                          </span>
                        )}
                      </p>
                    ) : (
                      <p style={{ margin: "4px 0 0 0", fontSize: "13px", color: "var(--gray-500)" }}>
                        No Proforma Invoice generated yet.
                      </p>
                    )}
                  </div>
                </div>

                {project.piStatus && (
                  <span
                    style={{
                      padding: "6px 12px",
                      borderRadius: "6px",
                      fontSize: "13px",
                      fontWeight: 500,
                      background: project.piStatus === "VERIFIED" ? "#dcfce7" : project.piStatus === "REJECTED" ? "#fee2e2" : "#fef9c3",
                      color: project.piStatus === "VERIFIED" ? "#166534" : project.piStatus === "REJECTED" ? "#991b1b" : "#854d0e",
                    }}
                  >
                    {project.piStatus === "VERIFIED" ? "✓ Verified" : project.piStatus === "REJECTED" ? "✗ Rejected" : "⏳ Pending"}
                  </span>
                )}
              </div>

              {project.piPdfUrl && (
                <div style={{ marginTop: "16px", display: "flex", gap: "8px" }}>
                  <a
                    href={`/api/projects/${project.id}/download-pi?inline=true`}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "6px",
                      padding: "6px 14px",
                      fontSize: "12px",
                      fontWeight: 500,
                      color: "#374151",
                      background: "#ffffff",
                      border: "1px solid #e2e8f0",
                      borderRadius: "6px",
                      textDecoration: "none",
                      boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
                    }}
                  >
                    <Eye size={14} />
                    View PI
                  </a>

                  <a
                    href={`/api/projects/${project.id}/download-pi`}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "6px",
                      padding: "6px 14px",
                      fontSize: "12px",
                      fontWeight: 600,
                      color: "#ffffff",
                      background: "linear-gradient(135deg, #4f46e5 0%, #4338ca 100%)",
                      border: "none",
                      borderRadius: "6px",
                      textDecoration: "none",
                      boxShadow: "0 2px 4px rgba(79, 70, 229, 0.15), 0 1px 2px rgba(0, 0, 0, 0.06)",
                    }}
                  >
                    <Download size={14} />
                    Download PI
                  </a>
                </div>
              )}
            </div>
          </div>

          {/* Documents & Files */}
          <div className="card">
            <div className="card-header">
              <h3 className="card-title">Documents & Files</h3>
            </div>
            <div className="card-body">
              <DocumentItem label="Purchase Order (PO)" files={poFiles} />
              <DocumentItem label="Delivery Challan" files={challanFiles} />
              <DocumentItem label="Tax Invoice" files={invoiceFiles} />
            </div>
          </div>
        </div>

        {/* Right Column - Timeline */}
        <div>
          <div className="card" style={{ position: 'sticky', top: '90px' }}>
            <div className="card-header">
              <h3 className="card-title">Project Timeline</h3>
            </div>
            <div className="card-body">
              <div className="timeline">
                {timelineSteps.map((step, i) => (
                  <div key={i} className="timeline-item">
                    <div className={`timeline-dot ${step.done ? 'completed' : step.active ? 'active' : 'pending'}`} />
                    <div className="timeline-content">
                      <h4 className="timeline-title">{step.title}</h4>
                      <div className="timeline-meta">
                        {step.date ? <><strong>Date:</strong> {formatDate(step.date)}</> : <span style={{ color: 'var(--gray-400)' }}>Pending</span>}
                      </div>
                      <p style={{ fontSize: '13px', color: 'var(--gray-600)', marginTop: '8px' }}>{step.note}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// View-only document list item component
function DocumentItem({ label, files }: { label: string; files: any[] }) {
  return (
    <div className="doc-section" style={{ background: 'var(--gray-50)', padding: '16px', borderRadius: '10px', marginBottom: '16px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
        <h4 style={{ fontWeight: 700, fontSize: '14px', color: 'var(--gray-900)' }}>{label}</h4>
      </div>

      {files.length > 0 ? (
        <div>
          {files.map((f) => (
            <div
              key={f.id}
              className="doc-item"
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '12px',
                background: 'var(--gray-0)',
                borderRadius: '6px',
                border: '1px solid var(--gray-200)',
                marginTop: '8px'
              }}
            >
              <div className="doc-info" style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <div className="doc-icon" style={{
                  width: '36px',
                  height: '36px',
                  background: 'var(--axis-primary)',
                  color: 'white',
                  borderRadius: '6px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontWeight: 700,
                  fontSize: '12px'
                }}>
                  PDF
                </div>
                <div>
                  <div style={{ fontWeight: 700, fontSize: '14px', color: 'var(--gray-900)', maxWidth: '180px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={f.filename}>{f.filename}</div>
                  <div style={{ fontSize: '12px', color: 'var(--gray-600)' }}>
                    Uploaded: {formatDate(f.uploadedAt)}
                  </div>
                </div>
              </div>
              <div className="doc-actions" style={{ display: 'flex', gap: '8px' }}>
                <a
                  href={`/api/files/${f.id}/view`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn btn-secondary"
                  style={{
                    padding: '6px 12px',
                    fontSize: '12px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    textDecoration: 'none'
                  }}
                  title="View file"
                >
                  <Eye size={14} />
                </a>
                <a
                  href={`/api/files/${f.id}/download`}
                  className="btn btn-secondary"
                  style={{
                    padding: '6px 12px',
                    fontSize: '12px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    textDecoration: 'none'
                  }}
                  title="Download file"
                  download
                >
                  <Download size={14} />
                </a>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <p style={{ color: 'var(--gray-500)', fontSize: '13px', margin: 0 }}>
          No documents uploaded
        </p>
      )}
    </div>
  )
}
