-- AlterTable
ALTER TABLE "collaterals" ADD COLUMN     "gstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "gstRate" DOUBLE PRECISION NOT NULL DEFAULT 18.0;

-- AlterTable
ALTER TABLE "projects" ADD COLUMN     "grandTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
